---
format:
  html:
    toc: false
    echo: false
---
```{r}
library(targets)

# for dependencies' sake
tar_load(acs_csvs)
```

```{ojs}
viewof state_selection = Inputs.select(state_data.map((d) => d.state_name), {label: "Select a state"})
```

# ${state_count} federal workers live in ${state_selection}

### Federal workers, by place of residence

::: {.panel-tabset}
## Congressional District
```{ojs}
Inputs.table(cd_filtered, {
  columns: [
    "geo_name",
    "federal_workers",
    "margin_of_error",
    "share_of_employment"
  ],
  width: "auto",
  header: {
    geo_name: "Congressional District",
    federal_workers: "Federal workers",
    margin_of_error: "Margin of error",
    share_of_employment: "Share of total employment"
  },
  format: {
    federal_workers: d3.format(",.0f"),
    margin_of_error: d3.format(",.0f"),
    share_of_employment: d3.format(".1%")
  },
  select: false,
  rows: 300
})
```

## County
```{ojs}
Inputs.table(county_filtered, {
  columns: [
    "geo_name",
    "federal_workers",
    "margin_of_error",
    "share_of_employment"
  ],
  width: "auto",
  header: {
    geo_name: "County",
    federal_workers: "Federal workers",
    margin_of_error: "Margin of error",
    share_of_employment: "Share of total employment"
  },
  format: {
    federal_workers: d3.format(",.0f"),
    margin_of_error: d3.format(",.0f"),
    share_of_employment: d3.format(".1%")
  },
  select: false,
  rows: 300
})
```

## Metro
```{ojs}
Inputs.table(metro_filtered, {
  columns: [
    "geo_name",
    "federal_workers",
    "margin_of_error",
    "share_of_employment"
  ],
  width: "auto",
  header: {
    geo_name: "Metro area",
    federal_workers: "Federal workers",
    margin_of_error: "Margin of error",
    share_of_employment: "Share of total employment"
  },
  format: {
    federal_workers: d3.format(",.0f"),
    margin_of_error: d3.format(",.0f"),
    share_of_employment: d3.format(".1%")
  },
  select: false,
  rows: 300
})
```

:::

```{ojs}
cd_download_text = "Download " + state_selection + " Congressional Districts" 

DOM.download(async () => {
  const csvString = d3.csvFormat([...cd_filtered]);
  return new Blob([csvString], { type: "text/csv" });
}, "federal_workers_cd_selections.csv", cd_download_text)
```

```{ojs}
county_download_text = "Download " + state_selection + " counties" 

DOM.download(async () => {
  const csvString = d3.csvFormat([...county_filtered]);
  return new Blob([csvString], { type: "text/csv" });
}, "federal_workers_county_selections.csv", county_download_text)
```

```{ojs}
metro_download_text = "Download " + state_selection + " metro areas" 

DOM.download(async () => {
  const csvString = d3.csvFormat([...metro_filtered]);
  return new Blob([csvString], { type: "text/csv" });
}, "federal_workers_metro_selections.csv", metro_download_text)
```

The data are based on the 2023 [American Community Survey](https://data.census.gov/table?t=Class%20of%20Worker&g=010XX00US,$0400000&d=ACS%201-Year%20Supplemental%20Estimates) 1-year estimates of civilian employment by class of worker and residence, and they extend the estimates previously published in [2024 Congressional Research Service report R47716](https://crsreports.congress.gov/product/pdf/R/R47716). The margin of error is for a 90% percent confidence interval. The share of total employment is the number of civilian federal workers divided by the number of all civilian workers living in a given location. Some small counties or areas may not be listed. Congressional Districts are for the 118th Congress.

This analysis rescales published ACS counts and margins of error so that the values above are consistent with the January 2025 BLS Current Employment Situation federal government employment [estimate](https://data.bls.gov/dataViewer/view/timeseries/CES9091000001) of 3,024,000 and total nonfarm employment [estimate](https://data.bls.gov/dataViewer/view/timeseries/CES0000000001) of 159,069,000.

To cite these data:

::: {.callout-note title="Reference"}
Analysis by Ben Zipperer, 18 February 2025, [Economic Policy Institute](https://www.epi.org/).
:::

View the [code](https://github.com/economic/federal_workforce), or download the data for every region at the level of [Congressional Districts](web_assets/federal_workers_cd.csv), [counties](web_assets/federal_workers_county.csv), [metro areas](web_assets/federal_workers_metro.csv), or [states](web_assets/federal_workers_state.csv).


```{ojs}
state_data = FileAttachment("web_assets/federal_workers_state.csv").csv({typed: true})
county_data = FileAttachment("web_assets/federal_workers_county.csv").csv({typed: true})
cd_data = FileAttachment("web_assets/federal_workers_cd.csv").csv({typed: true})
metro_data = FileAttachment("web_assets/federal_workers_metro.csv").csv({typed: true})

state_filtered = state_data
  .filter((d) => d.state_name == state_selection)

county_filtered = county_data
  .filter((d) => d.state_name == state_selection)

cd_filtered = cd_data
  .filter((d) => d.state_name == state_selection)

metro_filtered = metro_data
  .filter((d) => d.state_name == state_selection)

state_count = d3.format(",.0f")(state_filtered[0]['federal_workers'])

```

